/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BomRouteImport } from './routes/bom'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ShortagesRouteImport } from './routes/shortages'
import { Route as HubCodeRouteImport } from './routes/hub.$code'
import { Route as PartCodeRouteImport } from './routes/part.$code'
import { Route as PoIdRouteImport } from './routes/po.$id'
import { Route as SkuCodeRouteImport } from './routes/sku.$code'
import { Route as WorkerIdRouteImport } from './routes/worker.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortagesRoute = ShortagesRouteImport.update({
  id: '/shortages',
  path: '/shortages',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCodeRoute = HubCodeRouteImport.update({
  id: '/hub/$code',
  path: '/hub/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PartCodeRoute = PartCodeRouteImport.update({
  id: '/part/$code',
  path: '/part/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIdRoute = PoIdRouteImport.update({
  id: '/po/$id',
  path: '/po/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuCodeRoute = SkuCodeRouteImport.update({
  id: '/sku/$code',
  path: '/sku/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIdRoute = WorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/hubs': typeof HubsRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/shortages': typeof ShortagesRoute
  '/hub/$code': typeof HubCodeRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/worker/$id': typeof WorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/hubs': typeof HubsRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/shortages': typeof ShortagesRoute
  '/hub/$code': typeof HubCodeRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/worker/$id': typeof WorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bom': typeof BomRoute
  '/hubs': typeof HubsRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/shortages': typeof ShortagesRoute
  '/hub/$code': typeof HubCodeRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/worker/$id': typeof WorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bom'
    | '/hubs'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/shortages'
    | '/hub/$code'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/worker/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bom'
    | '/hubs'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/shortages'
    | '/hub/$code'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/worker/$id'
  id:
    | '__root__'
    | '/'
    | '/bom'
    | '/hubs'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/shortages'
    | '/hub/$code'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/worker/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BomRoute: typeof BomRoute
  HubsRoute: typeof HubsRoute
  OrdersRoute: typeof OrdersRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionRoute: typeof ProductionRoute
  ShortagesRoute: typeof ShortagesRoute
  HubCodeRoute: typeof HubCodeRoute
  PartCodeRoute: typeof PartCodeRoute
  PoIdRoute: typeof PoIdRoute
  SkuCodeRoute: typeof SkuCodeRoute
  WorkerIdRoute: typeof WorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortages': {
      id: '/shortages'
      path: '/shortages'
      fullPath: '/shortages'
      preLoaderRoute: typeof ShortagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$code': {
      id: '/hub/$code'
      path: '/hub/$code'
      fullPath: '/hub/$code'
      preLoaderRoute: typeof HubCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part/$code': {
      id: '/part/$code'
      path: '/part/$code'
      fullPath: '/part/$code'
      preLoaderRoute: typeof PartCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$id': {
      id: '/po/$id'
      path: '/po/$id'
      fullPath: '/po/$id'
      preLoaderRoute: typeof PoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sku/$code': {
      id: '/sku/$code'
      path: '/sku/$code'
      fullPath: '/sku/$code'
      preLoaderRoute: typeof SkuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/$id': {
      id: '/worker/$id'
      path: '/worker/$id'
      fullPath: '/worker/$id'
      preLoaderRoute: typeof WorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BomRoute: BomRoute,
  HubsRoute: HubsRoute,
  OrdersRoute: OrdersRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionRoute: ProductionRoute,
  ShortagesRoute: ShortagesRoute,
  HubCodeRoute: HubCodeRoute,
  PartCodeRoute: PartCodeRoute,
  PoIdRoute: PoIdRoute,
  SkuCodeRoute: SkuCodeRoute,
  WorkerIdRoute: WorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
